#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -o errexit
set -o pipefail
set -o nounset
if [[ "${TRACE-0}" == "1" ]]; then set -o xtrace; fi

# make our folders
mkdir -p \
    /config

# copy default config if not present in /config
if [[ ! -e /config/crontab.txt ]]; then
    cp /defaults/crontab.txt /config/crontab.txt
fi

# copy config from /config to system cronjob folder
mkdir -p /var/spool/cron/crontabs/
cp /config/crontab.txt /var/spool/cron/crontabs/root

# permissions
chown -R abc:abc \
    /config

chmod u+rwx -R \
    /config