#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -o errexit
set -o pipefail
set -o nounset
TRACE=1
if [[ "${TRACE-0}" == "1" ]]; then set -o xtrace; fi

# crond
# -f | Foreground
# -l N | Set log level. Most verbose 0, default 8
exec crond -f -l 2