---
name: Check for linting shell

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "**.sh"
  workflow_dispatch:

permissions: read-all
jobs:
  lint-shell-script:
    name: run shellcheck
    runs-on: ubuntu-latest
    if: (!startsWith(github.event.pull_request.head.ref, 'dependabot/') && !startsWith(github.event.pull_request.head.ref, 'renovate/') && github.event.head_commit.author.username != 'renovate-bot')

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
