---
name: Check for linting YML

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "**.yml"
      - "**.yaml"
  workflow_dispatch:

permissions: read-all
jobs:
  lint-shell-script:
    name: run yamllint
    runs-on: ubuntu-latest
    if: (!startsWith(github.event.pull_request.head.ref, 'dependabot/') && !startsWith(github.event.pull_request.head.ref, 'renovate/') && github.event.head_commit.author.username != 'renovate-bot')

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Run yamllint - *.yml
        run: yamllint -c .github/linters/yamllint_config.yaml ./
