---
name: Check for linting Markdown

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "**.md"
  workflow_dispatch:

permissions: read-all
jobs:
  lint-shell-script:
    name: run markdownlint
    runs-on: ubuntu-latest
    if: (!startsWith(github.event.pull_request.head.ref, 'dependabot/') && !startsWith(github.event.pull_request.head.ref, 'renovate/') && github.event.head_commit.author.username != 'renovate-bot')

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: DavidAnson/markdownlint-cli2-action@eb5ca3ab411449c66620fe7f1b3c9e10547144b0 # v18.0.0
        with:
          globs: "**/*.md"
