---
name: Check for linting github action

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - ".github/**.yml"
      - ".github/**.yaml"
  workflow_dispatch:

permissions: read-all
jobs:
  lint-shell-script:
    name: run github action linter
    runs-on: ubuntu-latest
    if: (!startsWith(github.event.pull_request.head.ref, 'dependabot/') && !startsWith(github.event.pull_request.head.ref, 'renovate/') && github.event.head_commit.author.username != 'renovate-bot')

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      - name: Display Go version
        run: go version
      - name: install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - name: run actionlint
        run: actionlint
