---
name: Check for linting Markdown

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "**.md"
  workflow_dispatch:

permissions: read-all
jobs:
  lint-shell-script:
    name: run markdownlint
    runs-on: ubuntu-latest
    if: (!startsWith(github.event.pull_request.head.ref, 'dependabot/') && !startsWith(github.event.pull_request.head.ref, 'renovate/') && github.event.head_commit.author.username != 'renovate-bot')

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: DavidAnson/markdownlint-cli2-action@510b996878fc0d1a46c8a04ec86b06dbfba09de7 # v15.0.0
        with:
          globs: "**/*.md"
