---
name: Run Tests

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "**.py"
      - tests
      - source
      - "*requirements*.txt"
      - "**poetry.lock"
      - "**pyproject.toml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction
      - name: Test with unittests
        run: |
          poetry run python -m unittest
