---
name: Run Tests

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "**.py"
      - tests
      - source
      - "*requirements*.txt"
      - "**poetry.lock"
      - "**pyproject.toml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --with dev
      - name: Test with unittests
        run: |
          poetry run python -m unittest
